[workspace]
authors = ["Ted Moore <ted@tedmooremusic.com>"]
channels = ["https://conda.modular.com/max-nightly", "conda-forge", "pytorch"]
name = "MMMAudio"
platforms = ["osx-arm64"]
version = "0.0.0"

[tasks.validate]
args = [
  { "arg" = "plots", "default" = "" }
]
cmd = "python validation/run_all.py {{ plots }}"

[dependencies]
mojo = "0.26.1.*"
numpy = ">=2.3.5,<3"
scipy = ">=1.17.0,<2"
librosa = ">=0.11.0,<0.12"
python = "3.13.*"
mido = ">=1.2.10,<2"
matplotlib = ">=3.10.8,<4"
pyside6 = ">=6.10.2,<7"
umap-learn = ">=0.5.11,<0.6"

[pypi-dependencies]
torch = ">=2.10.0, <3"
pyautogui = ">=0.9.54, <0.10"
python-osc = ">=1.9.3, <2"
python-rtmidi = ">=1.5.8, <2"
hidapi = ">=0.15.0, <0.16"
pyaudio = ">=0.2.14, <0.3"
