
from mmm_src.MMMWorld import MMMWorld

trait Graphable:
    fn next(mut self: Self) -> List[Float64]: ...

trait Buffable:
    fn read[N: Int = 1](mut self, start_chan: Int64, phase: Float64, interp: Int64 = 0) -> SIMD[DType.float64, N]: ...
    fn get_num_frames(self) -> Float64: ...
    fn get_duration(self) -> Float64: ...
    fn get_buf_sample_rate(self) -> Float64: ...