trait Buffable(Copyable, Movable):
    # fn read[N: Int = 1](mut self, start_chan: Int64, phase: Float64, interp: Int64 = 0) -> SIMD[DType.float64, N]: ...
    fn get_num_frames(self) -> Float64: ...
    # fn get_duration(self) -> Float64: ...
    # fn get_buf_sample_rate(self) -> Float64: ...
    fn get_item(self, chan_index: Int64, frame_index: Int64) -> Float64: ...
