name: Mojo Unit Tests

on:
  push:
    branches: [ dev, main ]
  pull_request:
    branches: [ dev, main ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  unit-tests:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.13.12'

      - name: brew installs
        run: |
          brew install portaudio
          brew install pixi

      - name: run 'pixi install'
        run: |
          pixi install

      - name: Run Tests
        id: run-tests
        run: |
          pixi run test_all