name: Mojo Unit Tests

on:
  push:
    branches: [ dev, main ]
  pull_request:
    branches: [ dev, main ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  unit-tests:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.13.12'

      - name: Install portaudio
        run: |
          brew install portaudio

      - name: Install pixi
        run: |
          brew install pixi

      - name: run 'pixi install'
        run: |
          pixi install

      # - name: Install Mojo
      #   run: |
      #     python -m pip install --upgrade pip
      #     pip install mojo==0.26.2.0
      
      # - name: Install Python Dependencies
      #   run: |
      #     pip install librosa numpy matplotlib scipy pyaudio

      - name: Print Versions
        run: |
          pixi run python --version
          pixi run mojo --version

      - name: Run UnitTests.mojo
        id: run-tests
        run: |
          mojo -debug-level=full testing_mmm_audio/UnitTests.mojo

      - name: Test Building Mojo Files
        run: |
          python testing_mmm_audio/test_build_mojo_files.py
        
      - name: Validate Against Snapshots
        run: |
          python testing_mmm_audio/validation/validate_against_snapshot.py
